/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ZonesRouteImport } from './routes/Zones'
import { Route as TermsOfUseRouteImport } from './routes/TermsOfUse'
import { Route as ResetPasswordRouteImport } from './routes/ResetPassword'
import { Route as RegisterRouteImport } from './routes/Register'
import { Route as ProfileRouteImport } from './routes/Profile'
import { Route as PaymentFormRouteImport } from './routes/PaymentForm'
import { Route as LoginRouteImport } from './routes/Login'
import { Route as LandingPageRouteImport } from './routes/LandingPage'
import { Route as HomePageRouteImport } from './routes/HomePage'
import { Route as ForgotPasswordRouteImport } from './routes/ForgotPassword'
import { Route as FaqRouteImport } from './routes/Faq'
import { Route as ContactFormRouteImport } from './routes/ContactForm'
import { Route as ChangePasswordRouteImport } from './routes/ChangePassword'
import { Route as CartRouteImport } from './routes/Cart'
import { Route as AdminUsersRouteImport } from './routes/AdminUsers'
import { Route as AdminReportsRouteImport } from './routes/AdminReports'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout/success'
import { Route as CheckoutCancelRouteImport } from './routes/checkout/cancel'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ZonesRoute = ZonesRouteImport.update({
  id: '/Zones',
  path: '/Zones',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/TermsOfUse',
  path: '/TermsOfUse',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/ResetPassword',
  path: '/ResetPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/Register',
  path: '/Register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/Profile',
  path: '/Profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFormRoute = PaymentFormRouteImport.update({
  id: '/PaymentForm',
  path: '/PaymentForm',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/Login',
  path: '/Login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPageRoute = LandingPageRouteImport.update({
  id: '/LandingPage',
  path: '/LandingPage',
  getParentRoute: () => rootRouteImport,
} as any)
const HomePageRoute = HomePageRouteImport.update({
  id: '/HomePage',
  path: '/HomePage',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/ForgotPassword',
  path: '/ForgotPassword',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/Faq',
  path: '/Faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactFormRoute = ContactFormRouteImport.update({
  id: '/ContactForm',
  path: '/ContactForm',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/ChangePassword',
  path: '/ChangePassword',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/Cart',
  path: '/Cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/AdminUsers',
  path: '/AdminUsers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/AdminReports',
  path: '/AdminReports',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutCancelRoute = CheckoutCancelRouteImport.update({
  id: '/checkout/cancel',
  path: '/checkout/cancel',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/AdminReports': typeof AdminReportsRoute
  '/AdminUsers': typeof AdminUsersRoute
  '/Cart': typeof CartRoute
  '/ChangePassword': typeof ChangePasswordRoute
  '/ContactForm': typeof ContactFormRoute
  '/Faq': typeof FaqRoute
  '/ForgotPassword': typeof ForgotPasswordRoute
  '/HomePage': typeof HomePageRoute
  '/LandingPage': typeof LandingPageRoute
  '/Login': typeof LoginRoute
  '/PaymentForm': typeof PaymentFormRoute
  '/Profile': typeof ProfileRoute
  '/Register': typeof RegisterRoute
  '/ResetPassword': typeof ResetPasswordRoute
  '/TermsOfUse': typeof TermsOfUseRoute
  '/Zones': typeof ZonesRoute
  '/about': typeof AboutRoute
  '/verify-email': typeof VerifyEmailRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/AdminReports': typeof AdminReportsRoute
  '/AdminUsers': typeof AdminUsersRoute
  '/Cart': typeof CartRoute
  '/ChangePassword': typeof ChangePasswordRoute
  '/ContactForm': typeof ContactFormRoute
  '/Faq': typeof FaqRoute
  '/ForgotPassword': typeof ForgotPasswordRoute
  '/HomePage': typeof HomePageRoute
  '/LandingPage': typeof LandingPageRoute
  '/Login': typeof LoginRoute
  '/PaymentForm': typeof PaymentFormRoute
  '/Profile': typeof ProfileRoute
  '/Register': typeof RegisterRoute
  '/ResetPassword': typeof ResetPasswordRoute
  '/TermsOfUse': typeof TermsOfUseRoute
  '/Zones': typeof ZonesRoute
  '/about': typeof AboutRoute
  '/verify-email': typeof VerifyEmailRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/AdminReports': typeof AdminReportsRoute
  '/AdminUsers': typeof AdminUsersRoute
  '/Cart': typeof CartRoute
  '/ChangePassword': typeof ChangePasswordRoute
  '/ContactForm': typeof ContactFormRoute
  '/Faq': typeof FaqRoute
  '/ForgotPassword': typeof ForgotPasswordRoute
  '/HomePage': typeof HomePageRoute
  '/LandingPage': typeof LandingPageRoute
  '/Login': typeof LoginRoute
  '/PaymentForm': typeof PaymentFormRoute
  '/Profile': typeof ProfileRoute
  '/Register': typeof RegisterRoute
  '/ResetPassword': typeof ResetPasswordRoute
  '/TermsOfUse': typeof TermsOfUseRoute
  '/Zones': typeof ZonesRoute
  '/about': typeof AboutRoute
  '/verify-email': typeof VerifyEmailRoute
  '/checkout/cancel': typeof CheckoutCancelRoute
  '/checkout/success': typeof CheckoutSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/AdminReports'
    | '/AdminUsers'
    | '/Cart'
    | '/ChangePassword'
    | '/ContactForm'
    | '/Faq'
    | '/ForgotPassword'
    | '/HomePage'
    | '/LandingPage'
    | '/Login'
    | '/PaymentForm'
    | '/Profile'
    | '/Register'
    | '/ResetPassword'
    | '/TermsOfUse'
    | '/Zones'
    | '/about'
    | '/verify-email'
    | '/checkout/cancel'
    | '/checkout/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/AdminReports'
    | '/AdminUsers'
    | '/Cart'
    | '/ChangePassword'
    | '/ContactForm'
    | '/Faq'
    | '/ForgotPassword'
    | '/HomePage'
    | '/LandingPage'
    | '/Login'
    | '/PaymentForm'
    | '/Profile'
    | '/Register'
    | '/ResetPassword'
    | '/TermsOfUse'
    | '/Zones'
    | '/about'
    | '/verify-email'
    | '/checkout/cancel'
    | '/checkout/success'
  id:
    | '__root__'
    | '/'
    | '/AdminReports'
    | '/AdminUsers'
    | '/Cart'
    | '/ChangePassword'
    | '/ContactForm'
    | '/Faq'
    | '/ForgotPassword'
    | '/HomePage'
    | '/LandingPage'
    | '/Login'
    | '/PaymentForm'
    | '/Profile'
    | '/Register'
    | '/ResetPassword'
    | '/TermsOfUse'
    | '/Zones'
    | '/about'
    | '/verify-email'
    | '/checkout/cancel'
    | '/checkout/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CartRoute: typeof CartRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ContactFormRoute: typeof ContactFormRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomePageRoute: typeof HomePageRoute
  LandingPageRoute: typeof LandingPageRoute
  LoginRoute: typeof LoginRoute
  PaymentFormRoute: typeof PaymentFormRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  ZonesRoute: typeof ZonesRoute
  AboutRoute: typeof AboutRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  CheckoutCancelRoute: typeof CheckoutCancelRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Zones': {
      id: '/Zones'
      path: '/Zones'
      fullPath: '/Zones'
      preLoaderRoute: typeof ZonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/TermsOfUse': {
      id: '/TermsOfUse'
      path: '/TermsOfUse'
      fullPath: '/TermsOfUse'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ResetPassword': {
      id: '/ResetPassword'
      path: '/ResetPassword'
      fullPath: '/ResetPassword'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Register': {
      id: '/Register'
      path: '/Register'
      fullPath: '/Register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Profile': {
      id: '/Profile'
      path: '/Profile'
      fullPath: '/Profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PaymentForm': {
      id: '/PaymentForm'
      path: '/PaymentForm'
      fullPath: '/PaymentForm'
      preLoaderRoute: typeof PaymentFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Login': {
      id: '/Login'
      path: '/Login'
      fullPath: '/Login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LandingPage': {
      id: '/LandingPage'
      path: '/LandingPage'
      fullPath: '/LandingPage'
      preLoaderRoute: typeof LandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/HomePage': {
      id: '/HomePage'
      path: '/HomePage'
      fullPath: '/HomePage'
      preLoaderRoute: typeof HomePageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ForgotPassword': {
      id: '/ForgotPassword'
      path: '/ForgotPassword'
      fullPath: '/ForgotPassword'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Faq': {
      id: '/Faq'
      path: '/Faq'
      fullPath: '/Faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ContactForm': {
      id: '/ContactForm'
      path: '/ContactForm'
      fullPath: '/ContactForm'
      preLoaderRoute: typeof ContactFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ChangePassword': {
      id: '/ChangePassword'
      path: '/ChangePassword'
      fullPath: '/ChangePassword'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Cart': {
      id: '/Cart'
      path: '/Cart'
      fullPath: '/Cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AdminUsers': {
      id: '/AdminUsers'
      path: '/AdminUsers'
      fullPath: '/AdminUsers'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AdminReports': {
      id: '/AdminReports'
      path: '/AdminReports'
      fullPath: '/AdminReports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/cancel': {
      id: '/checkout/cancel'
      path: '/checkout/cancel'
      fullPath: '/checkout/cancel'
      preLoaderRoute: typeof CheckoutCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminUsersRoute: AdminUsersRoute,
  CartRoute: CartRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ContactFormRoute: ContactFormRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomePageRoute: HomePageRoute,
  LandingPageRoute: LandingPageRoute,
  LoginRoute: LoginRoute,
  PaymentFormRoute: PaymentFormRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  ZonesRoute: ZonesRoute,
  AboutRoute: AboutRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  CheckoutCancelRoute: CheckoutCancelRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
